### ISSUE TITLE
jQuery error in Chromium, actions don't work

### ISSUE THREAD

**Issue by radzhome** [sehmaschine/django-grappelli#558]
I can only reproduce this in Chromium, its fine in Chrome.

Chromium version with issue:
Version 37.0.2062.120 Built on Ubuntu 12.04, running on elementary OS 0.2.1 (281580) (64-bit)

Chrome version where there is no issue:
Version 39.0.2171.95 (64-bit)

Never tried with Chromium 37.x but here is the issue:

```
<script>
            (function($) {
                $(document).ready(function() {
                    $("tr input.action-select").actions();  /* Uncaught TypeError: undefined is not a function
                });
            })(grp.jQuery);
</script>
```

It prevents actions from working.

**Comment by radlws** [comment]
Were you able to reproduce?

**Comment by radlws** [comment]
I'll update my Chromium and see, Thanks.

**Comment by radlws** [comment]
It started to occur in Chrome now, too Version 39.0.2171.95 (64-bit)  On OS X Mavericks

**Comment by radlws** [comment]
It would be more elegant if there was a button here instead, its not very informative/ responsive the way it is. I had the js error as well on 2 different machines using 2 different browsers.

**Comment by parsch** [comment]
Well, to be honest I think there's something wrong with your setup.
It works fine in Chrome 39.0.2171.95 (64-bit) on OS X Mavericks for me (and ever did).

Did you check if ```/static/admin/js/actions.js``` is loaded? I can reproduce the error if that's not the case...

**Comment by parsch** [comment]
And you might take a look at https://github.com/sehmaschine/django-grappelli/issues/214

**Comment by radlws** [comment]
static/admin/js/actions.js does load. I got it to work when I changed the
order of my static file loaders around to as suggested in 214:

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
 )

**Comment by lazerscience** [comment]
This (I think #214 is also related to this issue) drove me also nuts, my dev server continued to serve the Django version of `actions.js` though everything seemed to be configured properly.
After digging into this I found out that it is a caching issue (which is the reason people may experience it on some browsers and on others not - which may lead to the conclusion it is a browser related issue...):

* If you were using the original admin before your browser may still have a cached version of `action.js`, because if you configured your web server well to serve static files you've of course taken care of good caching - and - besides that the dev server also quite often responds with a `304 - Not Modified`.
* Running `collectstatic` and/or changing the order of your `STATICFILES_FINDERS` might lead to having the files served again, depending on how they are served (as it changes the file dates for examples).
* For me force-reload (shift-reload) suddenly solved the problem after fooling around for one hour :confused: .

So I think there's no real solution for that as long the Grappelli files have to share the same name as the ones that come with Django.
