### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#927]

**Comment by sehmaschine** [comment]
see d1e697a7dd5d342ba28cd7ecdeab62ed02df89ad

**Comment by StevenMapes** [comment]
**Bug** - TabularInlines do not clone the SELECT lists when using ```autocomplete_forms```

Versions:

- Django 3.0.2
- Grappelli 2.14.1 installed via ```git+https://github.com/sehmaschine/django-grappelli.git@stable/2.14.x```

The first element works but clicking "Add Another" does not retain the SELECT2 settings nor reinitialised the forms.

Example
```
class UserDBAccessInline(admin.TabularInline):
    model = UserDBAccess
    autocomplete_fields = ['user', 'db_name']
    can_delete = True
    extra = 1
    classes = ('grp-collapse grp-open',)
    inline_classes = ('grp-collapse grp-open',)

class UserAdmin(BaseUserAdmin):
    inlines = (UserDBAccessInline)

admin.site.unregister(User)
admin.site.register(User, UserAdmin)
```

The SELECT list that is created looks like this

````
<select name="db_access-1-databases" id="id_db_access-1-boxtop" class="admin-autocomplete" data-ajax--cache="true" data-ajax--delay="250" data-ajax--type="GET" data-ajax--url="/maze/common/databases/autocomplete/" data-theme="admin-autocomplete" data-allow-clear="false" data-placeholder="">
</select>
```

Where as the original rendered element is
```
<select name="db_access-0-databases" id="id_db_access-0-databases" class="admin-autocomplete select2-hidden-accessible" data-ajax--cache="true" data-ajax--delay="250" data-ajax--type="GET" data-ajax--url="/maze/common/boxtop/autocomplete/" data-theme="admin-autocomplete" data-allow-clear="false" data-placeholder="" tabindex="-1" aria-hidden="true">
</select>
````

So the SELECT2 classes are not being copied.

I have removed Grappelli and re-tested using the native Django Admin templates and those work.

**Comment by StevenMapes** [comment]
Related. I find that if you use both StackedInline and TabularInline classes within the same django admin page then SELECT2 errors. Though I can see that it is loading in both the Grappelli and normal Django admin autocomplete JS and CSS files (even with caching disabled within the browser). 

This results in both a JS warning and a JS error

```
jQuery.Deferred exception: $element.select2 is not a function TypeError: $element.select2 is not a function
    at init (http://127.0.0.1:8000/static/admin/js/autocomplete.js:14:18)
    at HTMLSelectElement.<anonymous> (http://127.0.0.1:8000/static/admin/js/autocomplete.js:21:13)
    at Function.each (http://127.0.0.1:8000/static/grappelli/jquery/jquery.min.js:2:2573)
    at e.fn.init.$.fn.djangoAdminSelect2 (http://127.0.0.1:8000/static/admin/js/autocomplete.js:19:11)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/static/admin/js/autocomplete.js:29:60)
    at l (http://127.0.0.1:8000/static/grappelli/jquery/jquery.min.js:2:29375)
    at c (http://127.0.0.1:8000/static/grappelli/jquery/jquery.min.js:2:29677) undefined


jquery.min.js:2 Uncaught TypeError: $element.select2 is not a function
    at init (autocomplete.js:14)
    at HTMLSelectElement.<anonymous> (autocomplete.js:21)
    at Function.each (jquery.min.js:2)
    at e.fn.init.$.fn.djangoAdminSelect2 (autocomplete.js:19)
    at HTMLDocument.<anonymous> (autocomplete.js:29)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
```

**Comment by sehmaschine** [comment]
@StevenMapes thanks for the extensive testing. we'll take a look asap.

**Comment by sehmaschine** [comment]
I've added a fix to stable/2.14.x which works with my setup. Please let me know if this also fixes your issue – if so, I'll do a release.

**Comment by StevenMapes** [comment]
I can confirm that the issues I was seeing with both TabularInline and StackedInline are both now working with Django 3.0.3 using the latest 2.14.x branch
